USE COMPANY;

-- TABLE USED IN THIS VIDEO (RUN BELOW QUERY TO CREATE EMPLOYEES TABLE) --
--------------------------------------------------------------------------
CREATE TABLE employees (
emp_id INT IDENTITY(1,1),
emp_name VARCHAR(100),
department VARCHAR(50),
salary INT,
city VARCHAR(50)
);

SET NOCOUNT ON;

DECLARE @i INT = 1;

WHILE @i <= 50000
BEGIN
INSERT INTO employees
VALUES (
'Employee_' + CAST(@i AS VARCHAR),
CASE
WHEN @i % 4 = 0 THEN 'IT'
WHEN @i % 4 = 1 THEN 'HR'
WHEN @i % 4 = 2 THEN 'Finance'
ELSE 'Sales'
END,
30000 + (@i % 20000),
CASE
WHEN @i % 3 = 0 THEN 'Bangalore'
WHEN @i % 3 = 1 THEN 'Hyderabad'
ELSE 'Chennai'
END
);

SET @i = @i + 1;

END;



-- SCRIPT EXPLAINED IN THIS VIDEO --
------------------------------------

-->> INDEXES

-->> WHAT IS INDEX?
--* INDEXES ARE DATABSE OBJECTS USED TO IMPROVE THE SPEED AND PERFORMANCE OF 
-- DATA RETRIEVAL.

-->> TYPES OF INDEXES
--* CLUSTERED INDEX
--* NON-CLUSTERED INDEX
--* UNIQUE INDEX
--* COMPOSITE INDEX

-->> CLUSTERED INDEX
SET STATISTICS TIME ON;

SELECT * FROM EMPLOYEES
WHERE EMP_ID = 40000;

SET STATISTICS TIME OFF;


CREATE INDEX EMP_ID_INDEX
ON EMPLOYEES(EMP_ID);

-- BEFORE INDEX - 8MS
-- AFTER INDEX - 2MS

-->> NON-CLUSTERED INDEX
EMPID EMPNAME   CLUSTERED INDEX    NON-CLUSTERED INDEX
1      A         1   A               1   - ROW NUMBER 1
3      N         2   K               2   - ROW NUMBER 3
2      K         3   N               3   - ROW NUMBER 2

CHAPTER 1     INDEX PAGE
CHAPTER 2     CHAPTER 1 - 1
CHAPTER 3     CHAPTER 2 - 4
              CHAPTER 3 - 8

CREATE NONCLUSTERED INDEX EMP_ID_INDEX
ON EMPLOYEES(EMP_ID);

-->> UNIQUE INDEX
SELECT * FROM EMPLOYEES;

CREATE UNIQUE INDEX EMP_ID_INDEX
ON EMPLOYEES(EMP_ID);

-->> COMPOSITE INDEX
CREATE INDEX EMP_ID_INDEX
ON EMPLOYEES(EMP_ID, SALARY);