USE COMPANY;
-----> TABLE USED IN THIS VIDEO (RUN BELOW QUERY TO CREATE EMPLOYEES TABLE) <-----
---------------------------------------
CREATE TABLE bank_accounts (
    account_id INT PRIMARY KEY,
    customer_name VARCHAR(50),
    balance DECIMAL(10,2)
);

INSERT INTO bank_accounts VALUES
(101, 'Ravi', 50000),
(102, 'Priya', 30000),
(103, 'Kiran', 45000);

CREATE TABLE employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(50),
    department VARCHAR(50),
    salary DECIMAL(10,2)
);

INSERT INTO employees VALUES
(1, 'Arjun', 'HR', 45000),
(2, 'Sneha', 'IT', 60000),
(3, 'Rahul', 'Finance', 55000);


-----> SCRIPT EXPLAINED IN THIS VIDEO <-----
--------------------------------------------

--> TCL -- ( TRANSACTION CONTROL LANGUAGE )
--> DCL -- ( DATA CONTROL LANGUAGE )

--> WHAT IS TCL?
--* TCL USED TO MANAGE TRANSACTIONS IN DATABASE.

--> WHAT IS TRANSACTION?
--* A GROUP OF SQL QUERIES EXECUTED TOGETHER AS ONE UNIT.

--* COMMIT
--* ROLLBACK
--* SAVE POINT / SAVE TRANSACTION

--> COMMIT
select * from bank_accounts;

-- SQL SERVER                        -- MYSQL SERVER
BEGIN TRANSACTION;                      START TRANSACTION;

UPDATE BANK_ACCOUNTS
SET BALANCE = BALANCE - 5000
WHERE ACCOUNT_ID = 101;

UPDATE BANK_ACCOUNTS
SET BALANCE = BALANCE + 5000
WHERE ACCOUNT_ID = 102;

COMMIT;

--> ROLLBACK
BEGIN TRANSACTION;

UPDATE BANK_ACCOUNTS
SET BALANCE = BALANCE - 10000 -- FOR SIPS (AUTO PAY)
WHERE ACCOUNT_ID = 101;

ROLLBACK;

--> SAVE POINT / SAVE TRANSACTION
-- STEPS TO COMPLETE ONLINE ORDER
--* 1 - CUSTOMER ADD PRODUCT TO HIS CART
--* 2 - SELLER SHOULD REDUCE STOCK IN STOCKS TABLE
--* 3 - OTP FOR PAYMENT

BEGIN TRANSACTION;

INSERT INTO CART (PRODUCT_ID, PRODUCT_NAME, QUANTITY) VALUES (101, 'LAPTOP', 1);

SAVE TRANSACTION ORDER_CREATED;

UPDATE STOCKS
SET STOCK = STOCK - 1
WHERE PRODUCT_ID = 101;

SAVE TRANSACTION STOCK_UPDATED;

SELECT OTP FROM OTPS_TABLE;

ROLLBACK TRANSACTION STOCK_UPDATED;
COMMIT;

--> DCL
--* GRANT
-- ADMINS -- HR -- EMPLOYEES
select * from employees;

GRANT SELECT, INSERT, UPDATE
ON EMPLOYEES
TO HR_USER;

--> REVOKE
REVOKE DELETE
ON EMPLOYEES
TO HR_USER;